// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVAQrAC4dCUuCJAec8Cxui3-_AoEwDmwM',
    appId: '1:831182489030:android:c4eddabceb20d59668dec7',
    messagingSenderId: '831182489030',
    projectId: 'glints-test-1c089',
    storageBucket: 'glints-test-1c089.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqjyaZDfXru_VVnO6XdSc5nRHCTM_hAjA',
    appId: '1:831182489030:ios:0d67586eb7a7364b68dec7',
    messagingSenderId: '831182489030',
    projectId: 'glints-test-1c089',
    storageBucket: 'glints-test-1c089.appspot.com',
    iosClientId: '831182489030-qbu3gebkmm6nl2k1ampck3bc5ik06f2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.glintTest',
  );
}
